### ISSUE TITLE
Resource not found: turtlebot3_bringup

### ISSUE THREAD

**Issue by antvkov** [aws-robotics/aws-robomaker-sample-application-cloudwatch#120]
Hi,

Previously I've successfully deployed _hello_world_robot_ application to turtlebot3 (raspberry pi3 with ubuntu 18.04 lts) in AWS Robomaker.
Currently I'm experiencing the following error while deploying _cloudwatch_robot_ application:

`ERROR: 2020/09/09 13:00:27 Command failed: exit status 1: [31mResource not found: turtlebot3_bringup
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/ggc_user/roboMakerDeploymentPackage/5cfcd2f27528023cc10db945a8ffbec132539e78bb31c1c0efb6cfcb92d06961/opt/built_workspace/cloudwatch_robot/share
ROS path [2]=/home/ggc_user/roboMakerDeploymentPackage/5cfcd2f27528023cc10db945a8ffbec132539e78bb31c1c0efb6cfcb92d06961/opt/built_workspace/turtlebot3_description_reduced_mesh/share
ROS path [3]=/home/ggc_user/roboMakerDeploymentPackage/5cfcd2f27528023cc10db945a8ffbec132539e78bb31c1c0efb6cfcb92d06961/opt/built_workspace/health_metric_collector/share
ROS path [4]=/home/ggc_user/roboMakerDeploymentPackage/5cfcd2f27528023cc10db945a8ffbec132539e78bb31c1c0efb6cfcb92d06961/opt/built_workspace/cloudwatch_metrics_collector/share
ROS path [5]=/home/ggc_user/roboMakerDeploymentPackage/5cfcd2f27528023cc10db945a8ffbec132539e78bb31c1c0efb6cfcb92d06961/opt/built_workspace/ros_monitoring_msgs/share
ROS path [6]=/home/ggc_user/roboMakerDeploymentPackage/5cfcd2f27528023cc10db945a8ffbec132539e78bb31c1c0efb6cfcb92d06961/opt/built_workspace/cloudwatch_logger/share
ROS path [7]=/home/ggc_user/roboMakerDeploymentPackage/5cfcd2f27528023cc10db945a8ffbec132539e78bb31c1c0efb6cfcb92d06961/opt/built_workspace/aws_ros1_common/share
ROS path [8]=/home/ggc_user/roboMakerDeploymentPackage/a4a7bacbb19213c72caa6c3cf1379e7e314efde0eca77c61ed3dfda0069bdcfe/opt/ros/melodic/share
ROS path [9]=/opt/ros/melodic/share[0m
[31mThe traceback for the exception was written to the log file[0m

`

I discovered that in _hello_world_robot_ in _turtlebot3_bringup.pc_ the prefix is set to _/opt/ros/melodic_, however in _cloudwatch_robot_ it is set to prefix=/home/ubuntu/environment/CloudWatch/simulation_ws/install/turtlebot3_bringup

Could it be the issue and could you please fix that?

**Comment by ahtsan** [comment]
@antvkov Thanks for using the Cloudwatch sample application. We are currently looking into the issue and will come back to you as soon as possible.

**Comment by ahtsan** [comment]
@antvkov It would be great if you can provide more information. How did you create the bundle for the robot application? How recently is it? Could you share the hash of the commit you used to create the bundle?

**Comment by antvkov** [comment]
@ahtsan I've created the bundle on the 4th of September using this guide [https://aws.amazon.com/blogs/robotics/deploy-robotic-applications-using-aws-robomaker/](url) with the following permissions [https://docs.aws.amazon.com/robomaker/latest/dg/sample-applications-permissions.html](url).

How can I check the hash in Robomaker Development environment?

**Comment by ahtsan** [comment]
> @ahtsan I've created the bundle on the 4th of September using this guide [https://aws.amazon.com/blogs/robotics/deploy-robotic-applications-using-aws-robomaker/](url) with the following permissions [https://docs.aws.amazon.com/robomaker/latest/dg/sample-applications-permissions.html](url).
> 
> How can I check the hash in Robomaker Development environment?

You can run `git log` in the repository where you built and bundled (step 14 in https://aws.amazon.com/blogs/robotics/deploy-robotic-applications-using-aws-robomaker/).

Also, which distro are you working on?

**Comment by ahtsan** [comment]
> > @ahtsan I've created the bundle on the 4th of September using this guide [https://aws.amazon.com/blogs/robotics/deploy-robotic-applications-using-aws-robomaker/](url) with the following permissions [https://docs.aws.amazon.com/robomaker/latest/dg/sample-applications-permissions.html](url).
> > How can I check the hash in Robomaker Development environment?
> 
> You can run `git log` in the repository where you built and bundled (step 14 in https://aws.amazon.com/blogs/robotics/deploy-robotic-applications-using-aws-robomaker/).
> 
> Also, which distro are you working on?

We were able to look up the environment so don't worry about the hash, and I think you are working on `melodic` right?

Could you share the location of `turtlebot3_bringup.pc`?

**Comment by ahtsan** [comment]
We are working on a fix.

**Comment by ahtsan** [comment]
Pull request created https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/pull/122

**Comment by ahtsan** [comment]
Pull request have been merged. I'm going to close this issue. Feel free to reopen it in case it's not working for you.

**Comment by antvkov** [comment]
@ahtsan Thank you, it works now.
