### ISSUE TITLE
Prefer installing packages via rosdep over downloading sources via .rosinstall

### ISSUE THREAD

**Issue by mm318** [aws-robotics/aws-robomaker-sample-application-cloudwatch#125]
It looks like ever since the release of this sample app (https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/commit/6469dad51c0b8c1df04a76cd824353ffe6f3cd0d#diff-55f9bb07b4449f6eb1c9e3c8685e55a4R4), the cloud extensions that it depends on have been fetched via source, even after said cloud extensions have already been bloom released. Installing the bloom released cloud extensions via `rosdep`/`apt` should be overwhelmingly preferred.

This issue is to track the removal of the cloud extension sources from the [`.rosinstall`](https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/blob/de116b387de7987fa7e6b82306c3f1e208fac997/robot_ws/.rosinstall) file.

**Comment by ojasjoshi** [comment]
https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/pull/131
