### ISSUE TITLE
Remove "turtlebot3" from .rosinstall

### ISSUE THREAD

**Issue by mm318** [aws-robotics/aws-robomaker-sample-application-cloudwatch#26]
https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/pull/25 was made for pulling in the fix at https://github.com/ROBOTIS-GIT/turtlebot3/pull/402, but once the fix is released and made available in the ros-melodic-turtlebot3-navigation apt package, https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/pull/25 should be reverted.

**Comment by xabxx** [comment]
@mm318 PR you referenced in this issue is merged. what's the next step?

**Comment by mm318** [comment]
I see that they have bloom released the https://github.com/ROBOTIS-GIT/turtlebot3/pull/402 fix. I don't think it has been synced yet, especially for the `melodic` distro.

Let's wait until after the sync in September to test and see if we can revert https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/pull/25.

**Comment by mm318** [comment]
This issue has been resolved by https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/pull/87.

**Comment by ahtsan** [comment]
This issue still needs verification.

**Comment by ahtsan** [comment]
Confirmed the fix has been synced in turtlebot3_navigation package
https://github.com/ROBOTIS-GIT/turtlebot3/commit/69b4563d754ad539d2b2c71fe6f968b3419fb3fb
