### ISSUE TITLE
Cloudwatch Metrics are published with a timestamp of several minutes in the future

### ISSUE THREAD

**Issue by juanrh** [aws-robotics/aws-robomaker-sample-application-cloudwatch#6]
This sample application have been affected by a [conversion error on the cloudwatch_metrics_collector node](https://github.com/aws-robotics/cloudwatchmetrics-ros1/issues/10). We have detected the problem, and we are working on deploying a fix, that should be available by the end of next week.

**Comment by juanrh** [comment]
The code fix was merged to the master and release-v1 branches of [cloudwatchmetrics-ros1](https://github.com/aws-robotics/cloudwatchmetrics-ros1). We are keeping this issue open until the fix is also available in our Apt packages

**Comment by juanrh** [comment]
The rosdep dependency it's now pointing to the fixed version of the cloudwatch_metrics_collector node, so the bug is fixed if this package is built from source as indicated in the [README](https://github.com/aws-robotics/aws-robomaker-sample-application-cloudwatch/blob/master/README.md). 

However I'm keeping this open until cloudwatch_metrics_collector is updated in Apt, which affects binary installs of cloudwatch_metrics_collector

**Comment by AAlon** [comment]
Closing this as the build procedure for this application already uses `rosws update` to fetch the hotfix (v1.0.1) of the affected package.
